### ISSUE TITLE
Years as units

### ISSUE THREAD

**Issue by sbacelar** [bluefoxr/COINr#1]
If you want to create an index for one country (no geo divisions) and you have data for the same indicators over several years, can years be considered as units in COINr?
If yes, does COINr have some adequate method for imputation of missing data (years)?

**Comment by bluefoxr** [comment]
Hi, you can assign units to anything you want, so yes you could only have one country and different points in time as different units. However, you need to keep in mind how subsequent operations will work, for example if you then normalise the data, it will normalise over time. If you impute, it will use simple methods such as mean, median or grouped means etc which are probably not ideal for a time series.

Time series data is slightly different because the order is important, we would expect two points close in time to be similar, for example. In COINr imputation is done without this information on proximity of units. You might want to consider a separate package for time series imputation.

Worth mentioning that now the assemble() function of COINr does allow a basic latest year imputation for panel data. I am slowly integrating panel data support bit it will take a while to get this up and running properly.

Check the function help files and also the online docum
