### ISSUE TITLE
paper.md language suggestions

### ISSUE THREAD

**Issue by paulrougieux** [bluefoxr/COINr#13]
Comments related to the JOSS review https://github.com/openjournals/joss-reviews/issues/4567

Line numbers refer to the version of paper.md on July 20 2022 at commit 1d9dce183cb59494c1ba870e014b5ae85442c283.

Line 40
> "fast development" ... " quick exploration"

The adjectives fast and quick can be removed, unless a documented comparison with other
tools can justify using these adjectives.

Line 50

> In Python there is a library called CIF which gives

Language suggestion:

The Python library CIF gives …

Line 54
> "full global sensitivity analysis"

This expression is repeated lines 40 and line 83. How does this differ from a
sensitivity analysis that would not be “full” and “global”? If this is a specific type
of sensitivity analysis, maybe this could be defined here?

**Comment by bluefoxr** [comment]
@paulrougieux thanks for these comments, I will make the suggested changes

**Comment by bluefoxr** [comment]
Hi, I've made edits to the paper to fix the issues: see commit https://github.com/bluefoxr/COINr/commit/a1340a02f488d45a6ccaee1182d025d8f7986493

For the global sensitivity analysis, I have left a reference because my understanding of JOSS papers is that they should be quite brief, so I would prefer to leave the explanation elsewhere. See if you think that is OK then I will close the issue or make some further edits. Thanks.

**Comment by paulrougieux** [comment]
The reference is ok.
